name: pipeline
on:
 push:
   branches:
     - "main"

permissions:
  packages: write

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
          push: true
          tags: |
            ghcr.io/alexraskin/test-web:latest
            ghcr.io/alexraskin/test-web:${{ github.sha }}
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: create env file
      run: |
        echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile
    
    - name: Tailscale
      uses: tailscale/github-action@v3
      with:
        authkey: ${{ secrets.TS_AUTH_KEY }}
        statedir: /tmp/tailscale-state/

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}

    - name: Deploy via Docker stack over Tailscale
      run: |
        TAILSCALE_HOST="${{ secrets.DEPLOY_HOST }}"

        scp -o StrictHostKeyChecking=no docker-compose.yml envfile ${{ secrets.DEPLOY_USER }}@$TAILSCALE_HOST:/tmp/

        ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@$TAILSCALE_HOST \
          "docker stack deploy -c /tmp/docker-compose.yml test-web --env-file /tmp/envfile"